# Generated by Django 6.0.6 on 2026-06-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(default=1, upload_to='players/'),
            preserve_default=False,
        ),
    ]
