# Generated by Django 6.0.6 on 2026-06-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0003_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='youtube_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
