# Generated by Django 5.0.2 on 2026-06-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0005_knockoutmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopScorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='scorers/')),
            ],
        ),
    ]
