# Generated by Django 5.0.2 on 2026-06-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0006_topscorer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Knockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('R16', 'Round of 16'), ('QF', 'Quarter Final'), ('SF', 'Semi Final'), ('F', 'Final')], max_length=10)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('match_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='KnockoutMatch',
        ),
    ]
