# Generated by Django 5.0.2 on 2026-06-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0007_knockout_delete_knockoutmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='knockout',
            name='away_logo',
            field=models.ImageField(blank=True, null=True, upload_to='teams/'),
        ),
        migrations.AddField(
            model_name='knockout',
            name='home_logo',
            field=models.ImageField(blank=True, null=True, upload_to='teams/'),
        ),
    ]
