# Generated by Django 5.0.2 on 2026-06-21 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0008_knockout_away_logo_knockout_home_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('status', models.CharField(default='Upcoming', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='worldcup.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='worldcup.team')),
            ],
        ),
    ]
