# Generated by Django 5.0.2 on 2026-06-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldcup', '0009_matchofday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchOfDay',
        ),
    ]
